import '@/assets/globals.css'
import { i18n } from '@/i18n-config'
import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'
import Providers from './providers'
import Navbar from '@/components/Navbar/Navbar'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

type MetadataProps = {
  params: {
    lang: 'fr' | 'en'
  }
}

const koulen = Koulen({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-koulen',
})

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: 'fr' | 'en' }
}) {
  return (
    <html lang={params.lang}>
      <body
        className={`min-h-screen min-w-full overflow-visible ${koulen.variable}`}
      >
        <Providers locale={params.lang}>{children}</Providers>
        <Navbar />
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Jo Thr • Website',
  description: 'Generated by create next app',
}
