import '@/assets/globals.css'
import { i18n } from '@/i18n-config'
import type { Metadata } from 'next'
import { Koulen } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import { getDictionary } from '@/hooks/getDictionary'
import Gradient from '@/components/Gradient/Gradient'
import Footer from '@/components/Footer/Footer'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

const koulen = Koulen({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-koulen',
})

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { locale: 'en' | 'fr' }
}) {
  const dictionary = await getDictionary(params.locale)
  return (
    <html lang={params.locale}>
      <body
        className={`min-h-screen min-w-full overflow-visible ${koulen.variable}`}
      >
        {children}
        <Navbar dataSummary={dictionary.summary} />
        <Gradient />
        <Footer data={dictionary.footer} />
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Jo Thr • Website',
  description: 'Generated by create next app',
}
