import '@/assets/globals.css'
import Footer from '@/components/Footer/Footer'
import Gradient from '@/components/Gradient/Gradient'
import Navbar from '@/components/Navbar/Navbar'
import { getDictionary } from '@/hooks/getDictionary'
import { i18n } from '@/i18n-config'
import MinLogo from '@public/images/LOGO-POINT.svg'
import '@splidejs/react-splide/css'
import { Allison, DM_Serif_Display, Poppins } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

const dm = DM_Serif_Display({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-dm-serif',
})

const allison = Allison({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-allison',
})

const poppins = Poppins({
  weight: ['400', '100', '200', '300', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: 'fr' | 'en' };
}) {
  const dictionary = await getDictionary(params.locale);
  return (
    <html lang={params.locale}>
      <body suppressHydrationWarning={true}
        className={`min-h-screen min-w-full overflow-visible ${dm.variable} ${allison.variable} ${poppins.variable}`}
      >
        <Link
          href={`/${params.locale}`}
          className="fixed top-[5vh] left-[3vw] z-50 w-[94vw] "
        >
          <Image src={MinLogo} alt={'Logo'} className="max-w-[2rem]" priority />
        </Link>
        {children}
        <Navbar
          dataSummary={dictionary.summary}
          content={dictionary.extraContent}
        />
        <Gradient />
        <Footer data={dictionary.footer} />
      </body>
    </html>
  )
}

export const metadata = {
  title: {
    default: 'Jo Thr • Website', // a default is required when creating a template
    template: `Jo Thr • %s`,
  },
  description: 'Generated by create next app',
}
