import {
  ArrowRight,
  ArrowUp,
  Award,
  CalendarCheck,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  X,
  Facebook,
  Globe,
  Home,
  Instagram,
  Linkedin,
  Mail,
  Phone,
  Plus,
  Printer,
  Settings,
  User,
  UserCheck,
  Youtube,
} from 'lucide-react'

export const ImageSVG = {
  ARROW_RIGHT: <ArrowRight />,
  ARROW_UP: <ArrowUp />,
  AWARD: <Award />,
  CALENDAR_CHECK: <CalendarCheck />,
  CAMERA: <Camera />,
  CHECK: <Check />,
  CHEVRON_DOWN: <ChevronDown />,
  CHEVRON_LEFT: <ChevronLeft />,
  CHEVRON_RIGHT: <ChevronRight />,
  CHEVRON_UP: <ChevronUp />,
  CROSS: <X />,
  FACEBOOK: <Facebook />,
  GLOBE: <Globe />,
  HOME: <Home />,
  INSTAGRAM: <Instagram />,
  LINKEDIN: <Linkedin />,
  MAIL: <Mail />,
  PHONE: <Phone />,
  PLUS: <Plus />,
  PRINTER: <Printer />,
  SETTINGS: <Settings />,
  USER: <User />,
  USER_CHECK: <UserCheck />,
  YOUTUBE: <Youtube />,
}

export enum IconType {
  ARROW_RIGHT = 'ARROW_RIGHT',
  ARROW_UP = 'ARROW_UP',
  AWARD = 'AWARD',
  CALENDAR_CHECK = 'CALENDAR_CHECK',
  CAMERA = 'CAMERA',
  CHECK = 'CHECK',
  CHEVRON_DOWN = 'CHEVRON_DOWN',
  CHEVRON_LEFT = 'CHEVRON_LEFT',
  CHEVRON_RIGHT = 'CHEVRON_RIGHT',
  CHEVRON_UP = 'CHEVRON_UP',
  CROSS = 'CROSS',
  FACEBOOK = 'FACEBOOK',
  GLOBE = 'GLOBE',
  HOME = 'HOME',
  INSTAGRAM = 'INSTAGRAM',
  LINKEDIN = 'LINKEDIN',
  MAIL = 'MAIL',
  PHONE = 'PHONE',
  PLUS = 'PLUS',
  PRINTER = 'PRINTER',
  SETTINGS = 'SETTINGS',
  USER = 'USER',
  USER_CHECK = 'USER_CHECK',
  YOUTUBE = 'YOUTUBE',
}
